### ISSUE TITLE
ProGaurd Issue

### ISSUE THREAD

**Issue by sajorahasan** [PSD-Company/duo-navigation-drawer#1]
Please provide progaurd file
App force closing as resources are missing res/drawable/duo_shape_rectangled_rounded_color_accent.xml
` Caused by: android.view.InflateException: Binary XML file line #8: Error inflating class nl.psdcompany.duonavigationdrawer.views.DuoMenuView
                                                                         at android.view.LayoutInflater.createView(LayoutInflater.java:620)
                                                                         at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
                                                                         at android.support.v7.app.k.b(Unknown Source)
                                                                         at android.support.v7.app.c.setContentView(Unknown Source)
                                                                         at com.ingridtech.fabric.ui.activity.HomeActivity.onCreate(Unknown Source)
                                                                         at android.app.Activity.performCreate(Activity.java:5231)
                                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233) 
                                                                         at android.app.ActivityThread.access$800(ActivityThread.java:135) 
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                         at android.os.Looper.loop(Looper.java:136) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5001) 
                                                                         at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                         at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
                                                                         at dalvik.system.NativeStart.main(Native Method) 
                                                                      Caused by: java.lang.reflect.InvocationTargetException
                                                                         at java.lang.reflect.Constructor.constructNative(Native Method)
                                                                         at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
                                                                         at android.view.LayoutInflater.createView(LayoutInflater.java:594)
                                                                         at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696) 
                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:755) 
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
                                                                         at android.support.v7.app.k.b(Unknown Source) 
                                                                         at android.support.v7.app.c.setContentView(Unknown Source) 
                                                                         at com.ingridtech.fabric.ui.activity.HomeActivity.onCreate(Unknown Source) 
                                                                         at android.app.Activity.performCreate(Activity.java:5231) 
                                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148) 
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233) 
                                                                         at android.app.ActivityThread.access$800(ActivityThread.java:135) 
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                         at android.os.Looper.loop(Looper.java:136) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5001) 
                                                                         at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                         at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
                                                                         at dalvik.system.NativeStart.main(Native Method) 
                                                                      Caused by: android.view.InflateException: Binary XML file line #6: Error inflating class Button
                                                                         at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:713)
                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                                                                         at nl.psdcompany.duonavigationdrawer.views.DuoMenuView.d(Unknown Source)
                                                                         at nl.psdcompany.duonavigationdrawer.views.DuoMenuView.a(Unknown Source)
                                                                         at nl.psdcompany.duonavigationdrawer.views.DuoMenuView.<init>(Unknown Source)
                                                                         at nl.psdcompany.duonavigationdrawer.views.DuoMenuView.<init>(Unknown Source)
                                                                         at java.lang.reflect.Constructor.constructNative(Native Method) 
                                                                         at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
                                                                         at android.view.LayoutInflater.createView(LayoutInflater.java:594) 
                                                                         at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696) 
                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:755) 
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
                                                                         at android.support.v7.app.k.b(Unknown Source) 
                                                                         at android.support.v7.app.c.setContentView(Unknown Source) 
                                                                         at com.ingridtech.fabric.ui.activity.HomeActivity.onCreate(Unknown Source) 
                                                                         at android.app.Activity.performCreate(Activity.java:5231) 
                                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148) 
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233) 
                                                                         at android.app.ActivityThread.access$800(ActivityThread.java:135) 
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                         at android.os.Looper.loop(Looper.java:136) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5001) 
                                                                         at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                         at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
                                                                         at dalvik.system.NativeStart.main(Native Method) 
                                                                      Caused by: android.content.res.Resources$NotFoundException: File res/drawable/duo_shape_rectangled_rounded_color_accent.xml from drawable resource ID #0x7f020063
                                                                         at android.content.res.Resources.loadDrawable(Resources.java:2096)
                                                                         at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
                                                                         at android.view.View.<init>(View.java:3554)
                                                                         at android.widget.TextView.<init>(TextView.java:623)
                                                                         at android.widget.Button.<init>(Button.java:107)
                                                                         at android.support.v7.widget.i.<init>(Unknown Source)
                                                                         at android.support.v7.widget.i.<init>(Unknown Source)
                                                                         at android.support.v7.app.m.a(Unknown Source)
                                                                         at android.support.v7.app.k.c(Unknown Source)
                                                                         at android.support.v7.app.k.a(Unknown Source)
                                                                         at android.support.v4.i.l$a.onCreateView(Unknown Source)
                                                                         at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:684)
                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:755) 
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                                                                         at nl.psdcompany.duonavigationdrawer.views.DuoMenuView.d(Unknown Source) 
                                                                         at nl.psdcompany.duonavigationdrawer.views.DuoMenuView.a(Unknown Source) 
                                                                         at nl.psdcompany.duonavigationdrawer.views.DuoMenuView.<init>(Unknown Source) 
                                                                         at nl.psdcompany.duonavigationdrawer.views.DuoMenuView.<init>(Unknown Source) 
                                                                         at java.lang.reflect.Constructor.constructNative(Native Method) 
                                                                         at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
                                                                         at android.view.LayoutInflater.createView(LayoutInflater.java:594) 
                                                                         at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696) 
                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:755) 
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
                                                                         at android.support.v7.app.k.b(Unknown Source) 
                                                                         at android.support.v7.app.c.setContentView(Unknown Source) 
                                                                         at com.ingridtech.fabric.ui.activity.HomeActivity.onCreate(Unknown Source) 
                                                                         at android.app.Activity.performCreate(Activity.java:5231) 
                                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148) 
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233) 
                                                                         at android.app.ActivityThread.access$800(ActivityThread.java:135) 
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                         at android.os.Looper.loop(Looper.java:136) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5001) 
                                                                         at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                         at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
                                                                         at dalvik.system.NativeStart.main(Native Method) 
                                                                      Caused by: java.lang.UnsupportedOperationException: Can't convert to color: type=0x2
                                                                         at android.content.res.TypedArray.getColor(TypedArray.java:327)
                                                                     	at android.graphics.drawable.GradientDrawable.inf`

**Comment by sajorahasan** [comment]
Issue solved in 2.0.1 
Earlier i was using 2.0.0
