### ISSUE TITLE
Binary XML file line #2: Binary XML file line #2: Error inflating class menu

### ISSUE THREAD

**Issue by mahirozdin** [PSD-Company/duo-navigation-drawer#27]
Error:
` FATAL EXCEPTION: main
                  Process: com.videodownloader.twittervideoindir, PID: 5182
                  android.view.InflateException: Binary XML file line #2: Binary XML file line #2: Error inflating class menu
                  Caused by: android.view.InflateException: Binary XML file line #2: Error inflating class menu
                  Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.menu" on path: DexPathList[[zip file "/data/app/com.videodownloader.twittervideoindir-mFHpn-U89LuLmlq_n7RsfQ==/base.apk", zip file "/data/app/com.videodownloader.twittervideoindir-mFHpn-U89LuLmlq_n7RsfQ==/split_lib_dependencies_apk.apk", zip file "/data/app/com.videodownloader.twittervideoindir-mFHpn-U89LuLmlq_n7RsfQ==/split_lib_resources_apk.apk", zip file "/data/app/com.videodownloader.twittervideoindir-mFHpn-U89LuLmlq_n7RsfQ==/split_lib_slice_0_apk.apk", zip file "/data/app/com.videodownloader.twittervideoindir-mFHpn-U89LuLmlq_n7RsfQ==/split_lib_slice_1_apk.apk", zip file "/data/app/com.videodownloader.twittervideoindir-mFHpn-U89LuLmlq_n7RsfQ==/split_lib_slice_2_apk.apk", zip file "/data/app/com.videodownloader.twittervideoindir-mFHpn-U89LuLmlq_n7RsfQ==/split_lib_slice_3_apk.apk", zip file "/data/app/com.videodownloader.twittervideoindir-mFHpn-U89LuLmlq_n7RsfQ==/split_lib_slice_4_apk.apk", zip file "/data/app/com.videodownloader.twittervideoindir-mFHpn-U89LuLmlq_n7RsfQ==/split_lib_slice_5_apk.apk", zip file "/data/app/com.videodownloader.twittervideoindir-mFHpn-U89LuLmlq_n7RsfQ==/split_lib_slice_6_apk.apk", zip file "/data/app/com.videodownloader.twittervideoindir-mFHpn-U89LuLmlq_n7RsfQ==/split_lib_slice_7_apk.apk", zip file "/data/app/com.videodownloader.twittervideoindir-mFHpn-U89LuLmlq_n7RsfQ==/split_lib_slice_8_apk.apk", zip file "/data/app/com.videodownloader.twittervideoindir-mFHpn-U89LuLmlq_n7RsfQ==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.videodownloader.twittervideoindir-mFHpn-U89LuLmlq_n7RsfQ==/lib/x86, /system/lib, /vendor/lib]]
                      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                      at android.view.LayoutInflater.createView(LayoutInflater.java:606)
                      at android.view.LayoutInflater.onCreateView(LayoutInflater.java:703)
                      at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:68)
                      at android.view.LayoutInflater.onCreateView(LayoutInflater.java:720)
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:788)
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                      at nl.psdcompany.duonavigationdrawer.views.DuoDrawerLayout.checkForMenuAttribute(DuoDrawerLayout.java:221)
                      at nl.psdcompany.duonavigationdrawer.views.DuoDrawerLayout.handleViews(DuoDrawerLayout.java:197)
                      at nl.psdcompany.duonavigationdrawer.views.DuoDrawerLayout.onLayout(DuoDrawerLayout.java:168)
                      at android.view.View.layout(View.java:19590)
                      at android.view.ViewGroup.layout(ViewGroup.java:6053)
                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                      at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                      at android.view.View.layout(View.java:19590)
                      at android.view.ViewGroup.layout(ViewGroup.java:6053)
                      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
                      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
                      at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
                      at android.view.View.layout(View.java:19590)
                      at android.view.ViewGroup.layout(ViewGroup.java:6053)
                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                      at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                      at android.view.View.layout(View.java:19590)
                      at android.view.ViewGroup.layout(ViewGroup.java:6053)
                      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
E/AndroidRuntime:     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
                      at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
                      at android.view.View.layout(View.java:19590)
                      at android.view.ViewGroup.layout(ViewGroup.java:6053)
                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                      at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                      at com.android.internal.policy.DecorView.onLayout(DecorView.java:758)
                      at android.view.View.layout(View.java:19590)
                      at android.view.ViewGroup.layout(ViewGroup.java:6053)
                      at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2484)
                      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2200)
                      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1386)
                      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6733)
                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
                      at android.view.Choreographer.doCallbacks(Choreographer.java:723)
                      at android.view.Choreographer.doFrame(Choreographer.java:658)
                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
                      at android.os.Handler.handleCallback(Handler.java:789)
                      at android.os.Handler.dispatchMessage(Handler.java:98)
                      at android.os.Looper.loop(Looper.java:164)
                      at android.app.ActivityThread.main(ActivityThread.java:6541)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                  	Suppressed: java.io.IOException: No original dex files found for dex location /data/app/com.videodownloader.twittervideoindir-mFHpn-U89LuLmlq_n7RsfQ==/split_lib_resources_apk.apk
                      at dalvik.system.DexFile.openDexFileNative(Native Method)
                      at dalvik.system.DexFile.openDexFile(DexFile.java:353)
                      at dalvik.system.DexFile.<init>(DexFile.java:100)
                      at dalvik.system.DexFile.<init>(DexFile.java:74)
                      at dalvik.system.DexPathList.loadDexFile(DexPathList.java:374)
                      at dalvik.system.DexPathList.makeDexElements(DexPathList.java:337)
                      at dalvik.system.DexPathList.<init>(DexPathList.java:157)
                      at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
                      at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
                      at com.android.internal.os.PathClassLoaderFactory.createClassLoader(PathClassLoaderFactory.java:43)
                      at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:69)
                      at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:36)
                      at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:676)
                      at android.app.LoadedApk.getClassLoader(LoadedApk.java:709)
                      at android.app.LoadedApk.getResources(LoadedApk.java:936)
                      at android.app.ContextImpl.createAppContext(ContextImpl.java:2242)
                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5672)
                      at android.app.ActivityThread.-wrap1(Unknown Source:0)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661)
                      at android.os.Handler.dispatchMessage(Handler.java:105)
                      		... 5 more`

Main Activity 
 ` protected void onCreate(Bundle savedInstanceState) {

        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        Toolbar toolbar = findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);

        DuoDrawerLayout drawerLayout = (DuoDrawerLayout) findViewById(R.id.draw);
        DuoDrawerToggle drawerToggle = new DuoDrawerToggle(this, drawerLayout, toolbar,
                R.string.navigation_drawer_open,
                R.string.navigation_drawer_close);

        drawerLayout.setDrawerListener(drawerToggle);
        drawerToggle.syncState();`

Main activity XML
`<nl.psdcompany.duonavigationdrawer.views.DuoDrawerLayout xmlns:android="http://schemas.android.com/apk/res/android"
   android:id="@+id/draw"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    app:menu="@menu/menu"
    app:content="@layout/content_main">
    <android.support.v7.widget.Toolbar
        android:minHeight="30dp"
        android:layout_width="match_parent"
        android:layout_height="30dp"
        android:background="@color/colorPrimary"
        android:id="@+id/toolbar"
        android:elevation="6dp" />
<FrameLayout
android:id="@+id/container"
android:layout_width="match_parent"
android:layout_height="match_parent"
android:tag="content"
 />
    <include layout="@layout/content_main" />

</nl.psdcompany.duonavigationdrawer.views.DuoDrawerLayout>`

Menu/menu.xml
`<?xml version="1.0" encoding="utf-8"?>
<menu xmlns:android="http://schemas.android.com/apk/res/android" >
    <Group android:checkableBehavior="single">
        <item
            android:id="@+id/nav_camera"
            android:icon="@drawable/ic_share"
            android:title="1234" />
        <item
            android:id="@+id/nav_camera2"
            android:icon="@drawable/ic_share"
            android:title="123" />
    </Group>
</menu>`

**Comment by mahirozdin** [comment]
Menu XML File

 `<?xml version="1.0" encoding="utf-8"?>
<menu xmlns:android="http://schemas.android.com/apk/res/android" >
    <Group android:checkableBehavior="single">
        <item
            android:id="@+id/nav_camera"
            android:icon="@drawable/ic_share"
            android:title="1234" />
        <item
            android:id="@+id/nav_camera2"
            android:icon="@drawable/ic_share"
            android:title="123" />
    </Group>
</menu>`
